package irctc.factor.app.irctcmadeeasy.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import irctc.factor.app.irctcmadeeasy.database.PnrInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PNR_INFO".
*/
public class PnrInfoDao extends AbstractDao<PnrInfo, Long> {

    public static final String TABLENAME = "PNR_INFO";

    /**
     * Properties of entity PnrInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PnrNo = new Property(1, Integer.class, "PnrNo", false, "PNR_NO");
        public final static Property PnrText = new Property(2, Integer.class, "PnrText", false, "PNR_TEXT");
    };


    public PnrInfoDao(DaoConfig config) {
        super(config);
    }
    
    public PnrInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PNR_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PNR_NO\" INTEGER," + // 1: PnrNo
                "\"PNR_TEXT\" INTEGER);"); // 2: PnrText
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PNR_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PnrInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer PnrNo = entity.getPnrNo();
        if (PnrNo != null) {
            stmt.bindLong(2, PnrNo);
        }
 
        Integer PnrText = entity.getPnrText();
        if (PnrText != null) {
            stmt.bindLong(3, PnrText);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PnrInfo readEntity(Cursor cursor, int offset) {
        PnrInfo entity = new PnrInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // PnrNo
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // PnrText
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PnrInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPnrNo(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPnrText(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PnrInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PnrInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
