package irctc.factor.app.irctcmadeeasy.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PNR_INFO".
 */
public class PnrInfo {

    private Long id;
    private Integer PnrNo;
    private Integer PnrText;

    public PnrInfo() {
    }

    public PnrInfo(Long id) {
        this.id = id;
    }

    public PnrInfo(Long id, Integer PnrNo, Integer PnrText) {
        this.id = id;
        this.PnrNo = PnrNo;
        this.PnrText = PnrText;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPnrNo() {
        return PnrNo;
    }

    public void setPnrNo(Integer PnrNo) {
        this.PnrNo = PnrNo;
    }

    public Integer getPnrText() {
        return PnrText;
    }

    public void setPnrText(Integer PnrText) {
        this.PnrText = PnrText;
    }

}
