package irctc.factor.app.irctcmadeeasy.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TICKET_DETAILS".
 */
public class TicketDetails {

    private Long id;
    private String Source;
    private String Destination;
    private String Boarding;
    private String JourneyDate;
    private String Trainno;
    private String IrctcClass;
    private String Quota;
    private String MobileNumber;
    private String Coach;
    private String AutoUpgrade;
    private String BookOnConfirm;
    private String conditionsOnBook;
    private String Json;

    public TicketDetails() {
    }

    public TicketDetails(Long id) {
        this.id = id;
    }

    public TicketDetails(Long id, String Source, String Destination, String Boarding, String JourneyDate, String Trainno, String IrctcClass, String Quota, String MobileNumber, String Coach, String AutoUpgrade, String BookOnConfirm, String conditionsOnBook, String Json) {
        this.id = id;
        this.Source = Source;
        this.Destination = Destination;
        this.Boarding = Boarding;
        this.JourneyDate = JourneyDate;
        this.Trainno = Trainno;
        this.IrctcClass = IrctcClass;
        this.Quota = Quota;
        this.MobileNumber = MobileNumber;
        this.Coach = Coach;
        this.AutoUpgrade = AutoUpgrade;
        this.BookOnConfirm = BookOnConfirm;
        this.conditionsOnBook = conditionsOnBook;
        this.Json = Json;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSource() {
        return Source;
    }

    public void setSource(String Source) {
        this.Source = Source;
    }

    public String getDestination() {
        return Destination;
    }

    public void setDestination(String Destination) {
        this.Destination = Destination;
    }

    public String getBoarding() {
        return Boarding;
    }

    public void setBoarding(String Boarding) {
        this.Boarding = Boarding;
    }

    public String getJourneyDate() {
        return JourneyDate;
    }

    public void setJourneyDate(String JourneyDate) {
        this.JourneyDate = JourneyDate;
    }

    public String getTrainno() {
        return Trainno;
    }

    public void setTrainno(String Trainno) {
        this.Trainno = Trainno;
    }

    public String getIrctcClass() {
        return IrctcClass;
    }

    public void setIrctcClass(String IrctcClass) {
        this.IrctcClass = IrctcClass;
    }

    public String getQuota() {
        return Quota;
    }

    public void setQuota(String Quota) {
        this.Quota = Quota;
    }

    public String getMobileNumber() {
        return MobileNumber;
    }

    public void setMobileNumber(String MobileNumber) {
        this.MobileNumber = MobileNumber;
    }

    public String getCoach() {
        return Coach;
    }

    public void setCoach(String Coach) {
        this.Coach = Coach;
    }

    public String getAutoUpgrade() {
        return AutoUpgrade;
    }

    public void setAutoUpgrade(String AutoUpgrade) {
        this.AutoUpgrade = AutoUpgrade;
    }

    public String getBookOnConfirm() {
        return BookOnConfirm;
    }

    public void setBookOnConfirm(String BookOnConfirm) {
        this.BookOnConfirm = BookOnConfirm;
    }

    public String getConditionsOnBook() {
        return conditionsOnBook;
    }

    public void setConditionsOnBook(String conditionsOnBook) {
        this.conditionsOnBook = conditionsOnBook;
    }

    public String getJson() {
        return Json;
    }

    public void setJson(String Json) {
        this.Json = Json;
    }

}
